language: cpp
dist: trusty
compiler:
   - gcc
   - clang

addons:
   apt:      
      packages:
         - cmake
         - doxygen

before_script:
   - wget http://mirrors.kernel.org/ubuntu/pool/main/libj/libjsoncpp/libjsoncpp1_1.7.2-1_amd64.deb -O libjsoncpp.deb
   - wget http://mirrors.kernel.org/ubuntu/pool/main/libj/libjsoncpp/libjsoncpp-dev_1.7.2-1_amd64.deb -O libjsoncpp-dev.deb
   - sudo dpkg --install libjsoncpp.deb
   - sudo dpkg --install libjsoncpp-dev.deb

script:
   - cmake . -DCMAKE_BUILD_TYPE="Release" -DCMAKE_CXX_FLAGS="-Wall -Wextra -O2 -finline-functions"
   - make -j3

before_deploy:
   - make docs
   - rm -rfv "*.cmake CMakeFiles CMakeCache.txt Makefile lib 
        src scripts include README.md .travis.yml 
        .gitignore Doxyfile CMakeLists.txt"
   - rm -r docs/latex
   - mv docs/html/* .

deploy:
   provider: pages
   skip_cleanup: true
   github_token: $GITHUB_TOKEN

