language: cpp
sudo: required
dist: trusty
compiler:
   - gcc
   - clang

addons:
   apt:      
      packages:
         - cmake
         - doxygen
	 - libgcrypt
	 - libgcrypt-dev
     
before_script:
   - sudo add-apt-repository ppa:deadsnakes/ppa -y
   - sudo add-apt-repository ppa:mstipicevic/ninja-build-1-7-2 -y
   - sudo apt update
   - sudo apt install -y python3.6 ninja-build
   - curl https://bootstrap.pypa.io/get-pip.py | sudo python3.6
   - sudo python3.6 -m pip install meson
   - bash scripts/jsoncpp.sh

script:
   - cmake . -DCMAKE_BUILD_TYPE="Release" -DCMAKE_CXX_FLAGS="-Wall -Wextra -O2 -finline-functions"
   - make -j3

before_deploy:
   - make docs
   - rm -rfv "*.cmake CMakeFiles CMakeCache.txt Makefile lib 
        src scripts include README.md .travis.yml 
        .gitignore Doxyfile CMakeLists.txt"
   - rm -r docs/latex
   - mv docs/html/* .

deploy:
   provider: pages
   skip_cleanup: true
   github_token: $GITHUB_TOKEN

